firstproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('signup.urls')),
    path('',include('homepage.urls')),
    path('',include('probec_main.urls')),
    path('admin/', admin.site.urls),

    #step5 fb login
    path('oauth/', include('social_django.urls', namespace='social')),  # <-- here
]

homepage/urls.py
from django.urls import path

from . import views

urlpatterns=[
    path('',views.homepage),
    path('homepage',views.homepage),
]

probec_main/urls.py
from django.urls import path

from . import views

app_name= 'pro_research'

urlpatterns=[
    path('dashboard',views.dashboard, name='dashboard'),
    path('product_research',views.product_research, name='product_research'),
    path('product_tracking',views.product_tracking, name='product_tracking'),
    path('comaprison',views.comaprison, name='comparison'),
    path('search',views.search, name='search'),
    path('searchptrack',views.searchptrack, name='searchptrack'),
    path('plot_graph',views.plot_graph, name='plot_graph'),
    path('market_analysis', views.market_analysis, name="market_analysis"),
    path('select_analysis',views.select_analysis, name='select_analysis'),
    path('search_comparison',views.search_comparison, name='search_comparison'),
    path('plot_graph_bar',views.plot_graph_bar, name='plot_graph_bar'),    
]

signup/urls.py
from django.urls import path

from . import views

urlpatterns=[
    path('register', views.register),
    path('signin', views.signin)
]

homepage/models.py
from django.db import models

# Create your models here.

signup/models.py
from django.db import models

# Create your models here.
class Userreg(models.Model):
    username=models.CharField(max_length=100)
    email=models.CharField(max_length=100)
    password=models.CharField(max_length=100)
    class Meta:
        db_table='users'
        app_label='signup.models.Userreg'

homepage/views.py
from django.shortcuts import render

# Create your views here.
def homepage(request):
    return render(request, 'homepage.html')

signup/views.py
from django.shortcuts import render, redirect

from signup.models import Userreg
from django.contrib import messages
from probec_main import views


def signin(request):
    if request.method == 'POST':
        try:
            userDetails=Userreg.objects.get(email=request.POST['email'], password=request.POST['password'])
            request.session['username']=userDetails.username
            return render(request, 'dashboard.html')

        except Userreg.DoesNotExist as e:
            messages.warning(request,"Invalid credentials")
            return render(request, 'signin.html')
    else:
        if request.session.has_key('username'):
            del request.session['username']
        return render(request, 'signin.html')
    
def register(request):
    if request.method == 'POST':
         #fetching data entered into textboxes
        if request.POST.get('username') and request.POST.get('email') and request.POST.get('password'):
            if request.POST.get('password') == request.POST.get('confirm_passowrd'):
                saverecord=Userreg()
                saverecord.username=request.POST['username']
                saverecord.email=request.POST['email']
                saverecord.password=request.POST['password']
                if Userreg.objects.filter(username=saverecord.username).exists():
                    messages.warning(request,"This username already exists!")
                    return render(request, 'signup.html')
                elif Userreg.objects.filter(email=saverecord.email).exists():
                    messages.warning(request,"This email already exists!")
                    return render(request, 'signup.html')
                else:
                    saverecord.save() 
                    messages.success(request,request.POST['username'] + " is registered at Probec successfully!")
                    return render(request, 'signup.html')  
            else: 
                messages.warning(request,"Password do not match!")
                return render(request, 'signup.html')
        else:
            messages.warning(request,"SORRY")
            return render(request, 'signup.html')
    else:
        #return HttpResponse(BASE_DIR)
        return render(request, 'signup.html')

templates/comparison.html
{% load static%}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Probec - Comparison</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <!-- Google fonts - Popppins for copy-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <!--orion icons-->
    <link rel="stylesheet" href="{% static 'css/orionicons.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Font awesome-->
    <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css" rel="stylesheet" type='text/css'>
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script src="https://cdn.plot.ly/plotly-2.2.0.min.js"></script>
    <style>
        .btn-success {
            background-color: #78afe6;
            color: #CCE0F4;
        }
        
        .btn-success:hover {
            background-color: #4499ee;
            border-color: #4499ee;
        }
    </style>
</head>

<body>
    <!-- navbar-->

    <div class="d-flex align-items-stretch">
        <div id="sidebar" class="sidebar shrink show py-3" style="height: 100%;
        position: fixed;
        z-index: 1;
        top: 0;
        left: 0;">
            <ul class="sidebar-menu list-unstyled">
                <li class="sidebar-list-item d-flex justify-content-start"><a href="#" id="pd-menu" class=" text-gray-500 ml-3 mr-lg-5 lead"><i class="fa fa-align-left"></i></a></li>
                <li class="sidebar-list-item">
                    <a href="dashboard" class="sidebar-link text-muted"><img src="{% static 'img/homepage.png' %}" alt="" class="mr-3" width="30" height="30"><span>Dashboard</span></a>
                </li>
                <li class="sidebar-list-item">
                    <a href="market_analysis" class="sidebar-link text-muted"><img src="{% static 'img/icons8-total-sales-50.png' %}" alt="" class="mr-3" width="30" height="30"><span>Market Analysis</span></a>
                </li>
                <li class="sidebar-list-item">
                    <a href="product_research" class="sidebar-link text-muted "><img src="{% static 'img/magnifying-glass.png' %}" alt="" class="mr-3" width="30" height="30"><span>Product Research</span></a>
                </li>
                <li class="sidebar-list-item">
                    <a href="product_tracking" class="sidebar-link text-muted "><img src="{% static 'img/keyword-research.png' %}" alt="" class="mr-3" width="30" height="30"></i><span>Product Tracking</span></a>
                </li>

                <li class="sidebar-list-item">
                    <a href="comaprison" class="sidebar-link text-muted active"><img src="{% static 'img/comparison.png' %}" alt="" class="mr-3" width="30" height="30"><span>Comparison </span></a>
                </li>
            </ul>
        </div>
        <div class="page-holder w-100 d-flex flex-wrap" style="margin-left: 7rem;align-content: flex-start;">
            <header class="header w-100 pb-1 mb-0" style="height:fit-content;">
                <nav class="navbar  px-4 py-2 bg-white shadow">
                    <a href="dashboard" class="navbar-brand"> <img src="{% static 'img/logo.png' %}" alt="" class="img-fluid logo" width="103" height="76"></a>
                    <ul class="ml-auto d-flex align-items-center list-unstyled mb-0">
                        <li class="nav-item dropdown ml-auto">
                            <a id="userInfo" href="http://example.com" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle"><img src="{% static 'img/user icon.png' %}" alt="Jason Doe" style="max-width: 2.5rem;" class="img-fluid rounded-circle shadow"></a>
                            <div aria-labelledby="userInfo" class="dropdown-menu"><a href="#" class="dropdown-item"><strong class="d-block text-uppercase headings-font-family">{{ user}}</strong></a>
                                <div class="dropdown-divider"></div><a href="signin" class="dropdown-item">Logout</a>
                            </div>
                        </li>
                    </ul>
                </nav>
            </header>
            <div class="container-fluid w-100 px-xl-5 pt-0">
                <form action="search_comparison" method="GET">
                    <h5 class="pb-4 pt-3">Comparison</h5>
                    <div class="row">

                        <div class="col-lg-4 col-md-4 col-sm-12"><input name="pro_f" id="pro_f" class="form-control mb-3" type="text" placeholder="First Product Name" aria-label="default input example"></div>
                        <div class="col-lg-4 col-md-4 col-sm-12"><input name="pro_s" id="pro_s" class="form-control mb-3" type="text" placeholder="Second Product Name" aria-label="default input example"></div>
                    </div>



                    <button type="submit" class="btn btn-success mt-3 mb-0">Generate Comparsion</button>
                </form>


                <div class="table-responsive mt-4" style="margin-top: -10%;">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col"></th>
                                <th scope="col">{{product_f | capfirst}}</th>
                                <th scope="col">{{product_s | capfirst}}</th>
                                <th scope="col">Actions</th>



                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">Avg Weekly Sales</th>
                                <td>{{average_sales_f}}</td>
                                <td>{{average_sales_s}}</td>
                                <td><button id2="{{average_sales_s}}" id1="{{average_sales_f}}" id="Sales" name_f="{{product_f}}" name_s="{{product_s}}" class="btn btn-primary triger-model">Generate Graph</td>

                            </tr>
                            <tr>
                                <th scope="row">Avg Weekly Revenue</th>
                                <td>{{average_revenue_f}}</td>
                                <td>{{average_revenue_s}}</td>
                                <td><button id2="{{average_revenue_s}}" id1="{{average_revenue_f}}" id="Revenue" name_f="{{product_f}}" name_s="{{product_s}}" class="btn btn-primary triger-model">Generate Graph</td>

                            </tr>
                            <tr>
                                <th scope="row" >Avg Price</th>
                                <td >{{average_price_f}}</td>
                                <td >{{average_price_s}}</td>
                                <td><button id2="{{average_price_s}}" id1="{{average_price_f}}" id="Price" name_f="{{product_f}}" name_s="{{product_s}}"  class="btn btn-primary triger-model" >Generate Graph</a></td>

                            </tr>
                            <tr>
                                <th scope="row" >Total Products</th>
                                <td >{{total_prod_f}}</td>
                                <td >{{total_prod_s}}</td>
                                <td><button id2="{{total_prod_s}}" id1="{{total_prod_f}}" id="Total Products" name_f="{{product_f}}" name_s="{{product_s}}"  class="btn btn-primary triger-model" >Generate Graph</a></td>


                            </tr>
                            <tr>
                                <th scope="row" >Total Brands</th>
                                <td >{{total_brand_f}}</td>
                                <td >{{total_brand_s}}</td>
                                <td><button id2="{{total_brand_s}}" id1="{{total_brand_f}}" id="Total Brands" name_f="{{product_f}}" name_s="{{product_s}}"  class="btn btn-primary triger-model" >Generate Graph</a></td>
                                    

                            </tr>
                            <tr>
                                <th scope="row" >Average Rating</th>
                                <td >{{average_rating_f}}</td>
                                <td >{{average_rating_s}}</td>
                                <td><button id2="{{average_rating_s}}" id1="{{average_rating_f}}" id="Rating" name_f="{{product_f}}" name_s="{{product_s}}"  class="btn btn-primary triger-model" >Generate Graph</a></td>

                            </tr>
                        </tbody>
                    </table>

                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-lg" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel"><span id="result_name"></span></h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                </div>
                <div class="modal-body">
                    <div id="graph_modal" class=" justify-content-center">
                    </div>
                </div>
            </div>
        </div>
    </div>


    </div>
    </div>

    </div>

    </div>

    <!--SCRIPT TO LOAD GRAPH IN MODAL-->
    <script>
        $(".triger-model").click(function(e) {
            e.preventDefault();
            $.ajax({
                url: "{% url 'pro_research:plot_graph_bar' %}",
                data: {
                    g_name: $(this).attr('id'),
                    value_f: $(this).attr('id1'),
                    value_s: $(this).attr('id2'),
                    name_f: $(this).attr('name_f'),
                    name_s: $(this).attr('name_s')
                },
                success: function(json) {
                    $('#exampleModal').modal("show");
                    document.getElementById("result_name").innerHTML = json['name'];
                    $('#graph_modal').html("{% autoescape off %}" + json['result'] + "{% endautoescape %}");

                },
                error: function(xhr, errmsg, er) {
                    alert(er + "," + errmsg);
                }
            });
        });
        $(".close").click(function(e) {
            $('#exampleModal').modal("hide");
        });
    </script>
    <!-- JavaScript files-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}">
    </script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}">
    </script>
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <script src="{% static 'js/charts-home.js' %}"></script>
    <script src="{% static 'js/front.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    <script>
        window.onload = function() {
            document.getElementById('close').onclick = function() {
                document.getElementById("card").style.display = "none";
            };
        };
    </script>
</body>

</html>

templates/dashboard.html
{% load static%}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Probec - Dashboard</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="{% static 'https://use.fontawesome.com/releases/v5.3.1/css/all.css' %}" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <!-- Google fonts - Popppins for copy-->
    <link rel="stylesheet" href="{% static 'https://fonts.googleapis.com/css?family=Poppins:300,400,800' %}">
    <!-- orion icons-->
    <link rel="stylesheet" href="{% static 'css/orionicons.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Font awesome-->
    <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css" rel="stylesheet" type='text/css'>
</head>

<body>
    <!-- navbar-->

    <div class="d-flex align-items-stretch">
        <div id="sidebar" class="sidebar shrink show py-3" style="height: 100%;
        position: fixed;
        z-index: 1;
        top: 0;
        left: 0;">
            <ul class="sidebar-menu list-unstyled">
                <li class="sidebar-list-item d-flex justify-content-start"><a href="#" id="pd-menu" class=" text-gray-500 ml-3 mr-lg-5 lead"><i class="fa fa-align-left"></i></a></li>
                <li class="sidebar-list-item">
                    <a href="dashboard" class="sidebar-link text-muted active"><img src="{% static 'img/homepage.png' %}" alt="" class="mr-3" width="30" height="30"><span>Dashboard</span></a>
                </li>
                <li class="sidebar-list-item">
                    <a href="market_analysis" class="sidebar-link text-muted"><img src="{% static 'img/icons8-total-sales-50.png' %}" alt="" class="mr-3" width="30" height="30"><span>Market Analysis</span></a>
                </li>
                <li class="sidebar-list-item">
                    <a href="product_research" class="sidebar-link text-muted "><img src="{% static 'img/magnifying-glass.png' %}" alt="" class="mr-3" width="30" height="30"><span>Product Research</span></a>
                </li>
                <li class="sidebar-list-item">
                    <a href="product_tracking" class="sidebar-link text-muted"><img src="{% static 'img/delivery.png' %}" alt="" class="mr-3" width="30" height="30"></i><span>Product Tracking</span></a>
                </li>

                <li class="sidebar-list-item">
                    <a href="comaprison" class="sidebar-link text-muted"><img src="{% static 'img/comparison.png' %}" alt="" class="mr-3" width="30" height="30"><span>Comparison </span></a>
                </li>
            </ul>
        </div>
        <div class="page-holder w-100 d-flex flex-wrap" style="margin-left: 7rem; align-content: flex-start;">
            <header class="header w-100" style="height:fit-content;">
                <nav class=" navbar px-4 py-2 bg-white shadow ">
                    <a href="dashboard " class="navbar-brand "> <img src="{% static 'img/PROBEC.png' %} " alt=" " class="img-fluid logo " width="103 " height="76 "></a>
                    <ul class="ml-auto d-flex align-items-center list-unstyled mb-0 ">
                        <li class="nav-item dropdown ml-auto">
                            <a id="userInfo" href="http://example.com" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle"><img src="{% static 'img/user icon.png' %}" style="max-width: 2.5rem;" class="img-fluid rounded-circle shadow"></a>
                            <div aria-labelledby="userInfo" class="dropdown-menu"><a href="#" class="dropdown-item"><strong class="d-block text-uppercase headings-font-family">{{ user }}</strong></a>
                                <div class="dropdown-divider"></div><a href="signin" class="dropdown-item">Logout</a>
                            </div>
                        </li>
                    </ul>
                </nav>
            </header>


            <div class="container-fluid px-xl-5 mt-3">
                <h5>Dashboard</h5>
                <h5 class="mt-4 mb-8">Welcome, {{ user }}</h5>
                <div class="d-flex align-self-start">
                    <!--<div class="col-sm-6" ><-->
                    <div class="toast show  mr-5 mt-5 w-50 toast-custom" " id="myToast1 " role="alert " aria-live="assertive " aria-atomic="true ">
                        <div class="toast-header p-3 " ">
                        <h6 class="me-auto ">Product Research</h6>
                        <button type="button " class="btn-close " id="btn1 " data-bs-dismiss="toast " aria-label="Close "></button>
                    </div>
                    <div class="toast-body p-3 ">
                        <p>This will help you find the best product to sell by showing you monthly sales, monthly revenue, review rating along with brand dominancy. These all features displayed about a particular product will help you pick the product which
                            will give you more profit.</p>
                        <a href="product_research " class="link dashboard-a ">Explore Tool</a>
                    </div>

                </div>
                <!--</div>
                    <div class="col-sm-6 ">-->
                <div class="toast show mr-5 mt-5 w-50 toast-custom" id="myToast2 " role="alert " aria-live="assertive " aria-atomic="true ">
                    <div class="toast-header p-3 ">
                        <h6 class="me-auto ">Product Tracking</h6>
                        <button type="button " class="btn-close " id="btn2 " data-bs-dismiss="toast " aria-label="Close "></button>
                    </div>
                    <div class="toast-body p-3 ">
                        <p>Have you launched your product and want to know its progress? Then this tool will help you analyze your product's progress through the help of weekly sales, predicted weekly sales and the reviews customers give to your product.
                            This will help you improve your product's progress accordingly.</p>
                        <a href="product_tracking " class="link dashboard-a ">Explore Tool</a>
                    </div>

                </div>

                <div class="toast show mr-5 mt-5 w-50 toast-custom" id="myToast3 " role="alert " aria-live="assertive " aria-atomic="true ">
                    <div class="toast-header p-3 ">
                        <h6 class="me-auto ">Market Analysis</h6>
                        <button type="button " class="btn-close " id="btn3" data-bs-dismiss="toast " aria-label="Close "></button>
                    </div>
                    <div class="toast-body p-3 ">
                        <p>This tool will help you to have a look at top 10 categories, brands and products of the week. It will display weekly sales data of the top 10 categories, brands or products. With the help of this tool you can easily identify that
                            whether is product lies in top 10 or not. You can also see that which category is the most sold so you can choose accordingly that which category's product you should launch.</p>
                        <a href="market_analysis" class="link dashboard-a ">Explore Tool</a>
                    </div>

                </div>
                <!--</div>
                <div class="row ">
                    
                    <div class="col-sm-6 ">-->
                <div id="myToast4" class="toast show mr-5 mt-5 w-50 toast-custom" role="alert " aria-live="assertive " aria-atomic="true ">
                    <div class="toast-header p-3">
                        <h6 class="me-auto ">Comparative Analysis</h6>
                        <button type="button " class="btn-close " id="btn4 " data-bs-dismiss="toast " aria-label="Close "></button>
                    </div>
                    <div class="toast-body p-3 ">
                        <p>You can decide after looking at the analysis that for which product you should go. This tool will show you a comparative analysis between 2 products either in tabular or graphical form, as per your choice.</p>
                        <a href="comaprison" class="link dashboard-a ">Explore Tool</a>
                    </div>

                </div>
                <!-- </div>-->

            </div>


        </div>

    </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js "></script>
    <script>
        $(document).ready(function(e) {
            $("#btn1").click(function() {
                $("#myToast1").toast("hide");
            });
            $("#btn2").click(function() {
                $("#myToast2").toast("hide");
            });
            $("#btn3").click(function() {
                $("#myToast3").toast("hide");
            });
            $("#btn4").click(function() {
                $("#myToast4").toast("hide");
            });
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js " integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p " crossorigin="anonymous "></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js " integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF " crossorigin="anonymous "></script>
    <script src="{% static 'vendor/jquery/jquery.min.js' %} "></script>
    <script src="{% static 'vendor/popper.js/umd/popper.min.js' %} ">
    </script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %} "></script>
    <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %} ">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js "></script>
    <script src="{% static 'js/front.js' %} "></script>

</body>

</html>